### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by xie-D-xq** [xyx1024/SimTxtSeg#1]
Hello author,your article is very good,but I would like to ask you how to put your data set?
For example,    dataset_vg = VGDataset("/mnt/data_ssd/yxxie/polyp/Downstream/images/train",
                           "/mnt/data_ssd/yxxie/polyp/Downstream/masks/train",
                           "polyp .",
                           "bert-base-uncased",
                           (512,512))
Do I need to create these folders myself, and then how do I move the data into these folders?

**Comment by xyx1024** [comment]
Yes, this code is used to test if the "VGDataset" is created successfully. Please create two new folders at any location you wish to store the images and mask paths of your training dataset, and pass them to the first two parameters of VGDataset.
